import { GoogleGenAI } from "@google/genai";
import { ImageSize, AspectRatio } from "../types";

// Helper to get the AI client. 
// We create a new instance each time to ensure we pick up the latest API key if it changes via the selection UI.
const getAiClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

/**
 * Generates an image using Gemini 3 Pro Image Preview (Nano Banana Pro).
 * This model supports high resolutions (up to 4K).
 */
export const generateImagePro = async (
  prompt: string,
  size: ImageSize = ImageSize.SIZE_1K,
  aspectRatio: AspectRatio = "1:1"
): Promise<string> => {
  const ai = getAiClient();
  
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        { text: prompt }
      ]
    },
    config: {
      imageConfig: {
        imageSize: size,
        aspectRatio: aspectRatio,
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image generated by the model.");
};

/**
 * Edits an image using Gemini 2.5 Flash Image.
 * Used for generating angle variations.
 */
export const editImageFlash = async (
  base64Image: string,
  prompt: string,
  aspectRatio: AspectRatio = "1:1"
): Promise<string> => {
  const ai = getAiClient();

  // Strip prefix if present for the API call
  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: cleanBase64,
            mimeType: 'image/png', // Assuming PNG for simplicity/compatibility
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: aspectRatio
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image variation generated.");
};

/**
 * "Upscales" an image by using Gemini 3 Pro with the original image as reference
 * and requesting a larger output size.
 */
export const upscaleImage = async (
  base64Image: string,
  prompt: string,
  targetSize: ImageSize = ImageSize.SIZE_4K
): Promise<string> => {
  const ai = getAiClient();
  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  // We treat upscaling as a high-fidelity generation with the image as context
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: cleanBase64,
            mimeType: 'image/png',
          },
        },
        {
          text: `High resolution, highly detailed version: ${prompt}`,
        },
      ],
    },
    config: {
      imageConfig: {
        imageSize: targetSize,
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("Failed to upscale image.");
};

// Check for API Key selection availability (specific to GCP projects for Pro models)
export const checkApiKeySelection = async (): Promise<boolean> => {
    if (window.aistudio && window.aistudio.hasSelectedApiKey) {
        return await window.aistudio.hasSelectedApiKey();
    }
    return true; // Default to true if not in the specific environment requiring selection
};

export const openApiKeySelection = async (): Promise<void> => {
    if (window.aistudio && window.aistudio.openSelectKey) {
        await window.aistudio.openSelectKey();
    }
};
